def hierabranch="goa"
def codebranch="goa"
pipeline {
   agent {label 'jenkins'}
    parameters {
        choice(choices: 'goa\nprod\nuat\ndev\nsit',  description: 'What environment?', name: 'env')
    }
    stages{
       stage('Preparation'){
         steps{
          script{
                if (params.env=="prod"){
                    hierabranch="master"
                    codebranch="prod"
                } else if (params.env=="uat"){
                    hierabranch="master"
                    codebranch="uat"
                } else if (params.env=="dev"){
                    hierabranch="master"
                    codebranch="dev"
                } else if (params.env=="sit"){ 
                    hierabranch="master"
                    codebranch="sit"
                }//if
                git branch: codebranch, url: 'https://github.com/vbkuzhel/puppetcode.git'
                sh 'tree'
                sh 'cd puppetcode/hieradata'
                sh 'tree'
//                withEnv(['hierabranch=${hierabranch}']) {
    
          }//script
         }//steps
       }//stage
    }//stages
}//pipeline              

