def hierabranch="goa"
def codebranch="goa"
pipeline {
   agent {label 'jenkins'}
    parameters {
        choice(choices: 'goa\nprod\nuat\ndev\nsit',  description: 'What environment?', name: 'env')
    }
    stages{
       stage('Preparation'){
         steps{
          script{
                if (params.env=="prod"){
                    hierabranch="master"
                    codebranch="prod"
                } else if (params.env=="uat"){
                    hierabranch="master"
                    codebranch="uat"
                } else if (params.env=="dev"){
                    hierabranch="master"
                    codebranch="dev"
                } else if (params.env=="sit"){ 
                    hierabranch="master"
                    codebranch="sit"
                }//if
                echo "hierabranch=${hierabranch},codebranch=${codebranch}"
                withEnv(['hierabranch=${hierabranch}', 'codebranch=${codebranch}']) {
    // some block
                sh '''
                        echo "hierabranch=${hierabranch},codebranch=${codebranch}"
                        git clone https://github.com/vbkuzhel/puppetcode.git thecode
                        git checkout "${codebranch}"
                        cd thecode/puppet/hieradata
                        git clone https://github.com/vbkuzhel/hieradata.git
                        git checkout "${hierabranch}"
                        cd ../../..
                        tree
                '''
                }

               /* witEnv(["hierabranch=${hierabranch}"]){
                    
                } */
          }//script
         }//steps
       }//stage
    }//stages
}//pipeline              

